### ISSUE TITLE
Add support for YAML themes in addition to JSON

### ISSUE THREAD

**Issue by erichoracek** [erichoracek/Motif#27]
Benefits:
- Only occasionally need to quote things
- Allows comments
- Way more readable

Drawbacks:
- Whitespace delimited
- No great YAML parsing libs, https://github.com/schwa/CocoaYAML seems to be the best, really just need a small wrapper around [LibYAML](http://pyyaml.org/wiki/LibYAML)

``` yaml
$BlueColor: "#50b5ed"
$FontName: AvenirNext-Regular
$RedColor: "#f93d38"
$WhiteColor: "#f1efeb"

# This is the root button class
.Button:
    borderColor: $BlueColor
    borderWidth: 1
    contentEdgeInsets: "{10, 20, 10, 20}"
    cornerRadius: 5
    tintColor: $BlueColor
    titleText: .ButtonText

.ButtonText:
    fontName: $FontName
    fontSize: 16

.ButtonsView:
    _superclass: .ContentBackground
    deleteButton: .WarningButton
    saveButton: .Button

.ContentBackground:
    backgroundColor: $WhiteColor

.WarningButton:
    _superclass: .Button
    borderColor: $RedColor
    tintColor: $RedColor
```
